import React from 'react'
// import './taple.css';
import Table from 'react-bootstrap/Table';

export default function Taple() {
    const dataTable =
        [
            {
                "sd": 34308,
                "oj": "20-093-22-1310-6",
                "odt": "2022-07-28T00:00:00",
                "opc": "Pc34308                                                                                                       ",
                "ofn": " ",
                "ocir": 527.1,
                "ofce": 1300,
                "ocy": 6,
                "ocs": "Cs84",
                "oprty": 6,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34309,
                "oj": "020-093-22-1305-08",
                "odt": "2022-07-28T00:00:00",
                "opc": "Pc34309                                                                                                       ",
                "ofn": " ",
                "ocir": 593.1,
                "ofce": 1300,
                "ocy": 8,
                "ocs": "Cs84",
                "oprty": 8,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34226,
                "oj": "",
                "odt": "2022-07-21T00:00:00",
                "opc": "Pc34226                                                                                                       ",
                "ofn": " ",
                "ocir": 521.1,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34698,
                "oj": "020-025-22-1302-08",
                "odt": "2022-09-05T00:00:00",
                "opc": "Pc34698                                                                                                       ",
                "ofn": " ",
                "ocir": 660,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs6",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 32793,
                "oj": "020-093-22-521-09",
                "odt": "2022-03-14T00:00:00",
                "opc": "Pc32793                                                                                                       ",
                "ofn": " ",
                "ocir": 541.5,
                "ofce": 1400,
                "ocy": 9,
                "ocs": "Cs84",
                "oprty": 9,
                "ostl": 9,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34843,
                "oj": "020-084-22-1491-07",
                "odt": "2022-09-20T00:00:00",
                "opc": "Pc34843                                                                                                       ",
                "ofn": " ",
                "ocir": 625,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs70",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-09-18T00:00:00"
            },
            {
                "sd": 34860,
                "oj": "20-027-22-1671-6",
                "odt": "2022-09-21T00:00:00",
                "opc": "Pc34860                                                                                                       ",
                "ofn": " ",
                "ocir": 500,
                "ofce": 1100,
                "ocy": 6,
                "ocs": "Cs17",
                "oprty": 6,
                "ostl": 6,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34862,
                "oj": "020-027-22-1673-09",
                "odt": "2022-09-21T00:00:00",
                "opc": "Pc34862                                                                                                       ",
                "ofn": " ",
                "ocir": 660,
                "ofce": 1100,
                "ocy": 9,
                "ocs": "Cs17",
                "oprty": 9,
                "ostl": 9,
                "orcy": 5,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34408,
                "oj": "",
                "odt": "2022-08-07T00:00:00",
                "opc": "Pc34408                                                                                                       ",
                "ofn": " ",
                "ocir": 656.1,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-07-27T00:00:00"
            },
            {
                "sd": 34431,
                "oj": "",
                "odt": "2022-08-09T00:00:00",
                "opc": "Pc34431                                                                                                       ",
                "ofn": " ",
                "ocir": 705,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs6",
                "oprty": 8,
                "ostl": 5,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34432,
                "oj": "",
                "odt": "2022-08-09T00:00:00",
                "opc": "Pc34432                                                                                                       ",
                "ofn": " ",
                "ocir": 705,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs6",
                "oprty": 8,
                "ostl": 0,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34896,
                "oj": "",
                "odt": "2022-09-25T00:00:00",
                "opc": "Pc34896                                                                                                       ",
                "ofn": " ",
                "ocir": 541.5,
                "ofce": 1300,
                "ocy": 10,
                "ocs": "Cs84",
                "oprty": 10,
                "ostl": 10,
                "orcy": 10,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 32641,
                "oj": "020-093-22-118-07",
                "odt": "2022-03-02T00:00:00",
                "opc": "Pc32641                                                                                                       ",
                "ofn": " ",
                "ocir": 512,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-03-01T00:00:00"
            },
            {
                "sd": 34171,
                "oj": "20-093-22-242-6",
                "odt": "2022-07-18T00:00:00",
                "opc": "Pc34171                                                                                                       ",
                "ofn": " ",
                "ocir": 677,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-06-15T00:00:00"
            },
            {
                "sd": 34645,
                "oj": "020-025-22-1172-08",
                "odt": "2022-08-29T00:00:00",
                "opc": "Pc34645                                                                                                       ",
                "ofn": " ",
                "ocir": 540,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs6",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34670,
                "oj": "020-084-22-1397-08",
                "odt": "2022-08-31T00:00:00",
                "opc": "Pc34670                                                                                                       ",
                "ofn": " ",
                "ocir": 660,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs70",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-08-30T00:00:00"
            },
            {
                "sd": 35106,
                "oj": "020-073-22-1066-08",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35106                                                                                                       ",
                "ofn": " ",
                "ocir": 566,
                "ofce": 1320,
                "ocy": 2,
                "ocs": "Cs49",
                "oprty": 1,
                "ostl": 0,
                "orcy": 2,
                "ohg": 1,
                "oComDt": "2022-10-16T00:00:00"
            },
            {
                "sd": 35107,
                "oj": "020-073-22-1066-08",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35107                                                                                                       ",
                "ofn": " ",
                "ocir": 566,
                "ofce": 1320,
                "ocy": 0,
                "ocs": "Cs49",
                "oprty": 0,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35108,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35108                                                                                                       ",
                "ofn": " ",
                "ocir": 600,
                "ofce": 1150,
                "ocy": 5,
                "ocs": "Cs50",
                "oprty": 5,
                "ostl": 0,
                "orcy": 5,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35109,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35109                                                                                                       ",
                "ofn": " ",
                "ocir": 550,
                "ofce": 1150,
                "ocy": 4,
                "ocs": "Cs50",
                "oprty": 4,
                "ostl": 0,
                "orcy": 4,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35110,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35110                                                                                                       ",
                "ofn": " ",
                "ocir": 590,
                "ofce": 1150,
                "ocy": 6,
                "ocs": "Cs50",
                "oprty": 6,
                "ostl": 0,
                "orcy": 6,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35111,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35111                                                                                                       ",
                "ofn": " ",
                "ocir": 600,
                "ofce": 1150,
                "ocy": 6,
                "ocs": "Cs50",
                "oprty": 6,
                "ostl": 2,
                "orcy": 6,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35112,
                "oj": "20-059-22-1451-7",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35112                                                                                                       ",
                "ofn": " ",
                "ocir": 650,
                "ofce": 1050,
                "ocy": 1,
                "ocs": "Cs43",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-13T00:00:00"
            },
            {
                "sd": 35113,
                "oj": "20-027-22-1148-8",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35113                                                                                                       ",
                "ofn": " ",
                "ocir": 540,
                "ofce": 1300,
                "ocy": 4,
                "ocs": "Cs17",
                "oprty": 4,
                "ostl": 0,
                "orcy": 4,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35114,
                "oj": "20-027-22-1150-8",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35114                                                                                                       ",
                "ofn": " ",
                "ocir": 540,
                "ofce": 1300,
                "ocy": 4,
                "ocs": "Cs17",
                "oprty": 4,
                "ostl": 0,
                "orcy": 4,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34489,
                "oj": "20-093-22-455-7",
                "odt": "2022-08-16T00:00:00",
                "opc": "Pc34489                                                                                                       ",
                "ofn": " ",
                "ocir": 551,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-08-16T00:00:00"
            },
            {
                "sd": 34974,
                "oj": "020-084-22-1649-08",
                "odt": "2022-10-03T00:00:00",
                "opc": "Pc34974                                                                                                       ",
                "ofn": " ",
                "ocir": 730,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs70",
                "oprty": 8,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34977,
                "oj": "020-084-22-1024-09",
                "odt": "2022-10-03T00:00:00",
                "opc": "Pc34977                                                                                                       ",
                "ofn": " ",
                "ocir": 510,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs70",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34980,
                "oj": "020-045-22-1647-01",
                "odt": "2022-10-03T00:00:00",
                "opc": "Pc34980                                                                                                       ",
                "ofn": " ",
                "ocir": 350,
                "ofce": 700,
                "ocy": 1,
                "ocs": "Cs2",
                "oprty": 1,
                "ostl": 1,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34981,
                "oj": "020-007-22-1669-09",
                "odt": "2022-10-03T00:00:00",
                "opc": "Pc34981                                                                                                       ",
                "ofn": " ",
                "ocir": 530,
                "ofce": 1400,
                "ocy": 9,
                "ocs": "Cs63",
                "oprty": 9,
                "ostl": 9,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34982,
                "oj": "020-007-22-1665-08",
                "odt": "2022-10-03T00:00:00",
                "opc": "Pc34982                                                                                                       ",
                "ofn": " ",
                "ocir": 530,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs63",
                "oprty": 8,
                "ostl": 8,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34983,
                "oj": "020-007-22-1648-08",
                "odt": "2022-10-03T00:00:00",
                "opc": "Pc34983                                                                                                       ",
                "ofn": " ",
                "ocir": 630,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs63",
                "oprty": 8,
                "ostl": 8,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 31491,
                "oj": "020-093-20-548-06",
                "odt": "2021-12-15T00:00:00",
                "opc": "Pc31491 ",
                "ofn": " ",
                "ocir": 574,
                "ofce": 1300,
                "ocy": 2,
                "ocs": "Cs84",
                "oprty": 2,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 32476,
                "oj": "020-002-22-59-08",
                "odt": "2022-02-20T00:00:00",
                "opc": "Pc32476                                                                                                       ",
                "ofn": " ",
                "ocir": 560,
                "ofce": 1500,
                "ocy": 2,
                "ocs": "Cs2106",
                "oprty": 0,
                "ostl": 0,
                "orcy": 2,
                "ohg": 2,
                "oComDt": "2022-02-17T00:00:00"
            },
            {
                "sd": 32485,
                "oj": "",
                "odt": "2022-02-21T00:00:00",
                "opc": "Pc32485                                                                                                       ",
                "ofn": " ",
                "ocir": 608.01,
                "ofce": 1400,
                "ocy": 3,
                "ocs": "Cs27",
                "oprty": 3,
                "ostl": 0,
                "orcy": 3,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 33551,
                "oj": "020-072-21-1818-08",
                "odt": "2022-05-22T00:00:00",
                "opc": "Pc33551                                                                                                       ",
                "ofn": " ",
                "ocir": 520,
                "ofce": 1320,
                "ocy": 1,
                "ocs": "Cs81",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-05-22T00:00:00"
            },
            {
                "sd": 34035,
                "oj": "020-025-22-736-08",
                "odt": "2022-07-03T00:00:00",
                "opc": "Pc34035                                                                                                       ",
                "ofn": " ",
                "ocir": 640,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs6",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34038,
                "oj": "020-025-22-758-07",
                "odt": "2022-07-03T00:00:00",
                "opc": "Pc34038                                                                                                       ",
                "ofn": " ",
                "ocir": 640,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs6",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34998,
                "oj": "20-075-22-1640-4",
                "odt": "2022-10-05T00:00:00",
                "opc": "Pc34998                                                                                                       ",
                "ofn": " ",
                "ocir": 639,
                "ofce": 600,
                "ocy": 4,
                "ocs": "Cs2109",
                "oprty": 4,
                "ostl": 4,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35002,
                "oj": "20-075-22-1482-4",
                "odt": "2022-10-05T00:00:00",
                "opc": "Pc35002                                                                                                       ",
                "ofn": " ",
                "ocir": 520,
                "ofce": 455,
                "ocy": 1,
                "ocs": "Cs2109",
                "oprty": 0,
                "ostl": 1,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-05T00:00:00"
            },
            {
                "sd": 35010,
                "oj": "20-042-22-1659-8",
                "odt": "2022-10-09T00:00:00",
                "opc": "Pc35010                                                                                                       ",
                "ofn": " ",
                "ocir": 500,
                "ofce": 1300,
                "ocy": 8,
                "ocs": "Cs25",
                "oprty": 8,
                "ostl": 3,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35023,
                "oj": "20-075-22-1650-6",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35023                                                                                                       ",
                "ofn": " ",
                "ocir": 440,
                "ofce": 600,
                "ocy": 4,
                "ocs": "Cs2109",
                "oprty": 4,
                "ostl": 4,
                "orcy": 4,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35024,
                "oj": "",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35024                                                                                                       ",
                "ofn": " ",
                "ocir": 550,
                "ofce": 1400,
                "ocy": 7,
                "ocs": "Cs63",
                "oprty": 7,
                "ostl": 0,
                "orcy": 7,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35025,
                "oj": "",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35025                                                                                                       ",
                "ofn": " ",
                "ocir": 580,
                "ofce": 1400,
                "ocy": 6,
                "ocs": "Cs63",
                "oprty": 6,
                "ostl": 0,
                "orcy": 6,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35026,
                "oj": "",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35026                                                                                                       ",
                "ofn": " ",
                "ocir": 550,
                "ofce": 1400,
                "ocy": 7,
                "ocs": "Cs63",
                "oprty": 7,
                "ostl": 0,
                "orcy": 7,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35027,
                "oj": "",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35027                                                                                                       ",
                "ofn": " ",
                "ocir": 580,
                "ofce": 1400,
                "ocy": 7,
                "ocs": "Cs63",
                "oprty": 7,
                "ostl": 0,
                "orcy": 7,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35028,
                "oj": "",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35028                                                                                                       ",
                "ofn": " ",
                "ocir": 580,
                "ofce": 1400,
                "ocy": 6,
                "ocs": "Cs63",
                "oprty": 6,
                "ostl": 0,
                "orcy": 6,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35033,
                "oj": "20-059-22-1658-5",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35033                                                                                                       ",
                "ofn": " ",
                "ocir": 633,
                "ofce": 1050,
                "ocy": 5,
                "ocs": "Cs43",
                "oprty": 5,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35034,
                "oj": "20-059-22-1660-7",
                "odt": "2022-10-10T00:00:00",
                "opc": "Pc35034                                                                                                       ",
                "ofn": " ",
                "ocir": 633,
                "ofce": 1050,
                "ocy": 7,
                "ocs": "Cs43",
                "oprty": 7,
                "ostl": 1,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35040,
                "oj": "020-093-22-1675-07",
                "odt": "2022-10-11T00:00:00",
                "opc": "Pc35040                                                                                                       ",
                "ofn": " ",
                "ocir": 502,
                "ofce": 1400,
                "ocy": 7,
                "ocs": "Cs84",
                "oprty": 7,
                "ostl": 7,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 34066,
                "oj": "020-093-21-2142-08",
                "odt": "2022-07-04T00:00:00",
                "opc": "Pc34066                                                                                                       ",
                "ofn": " ",
                "ocir": 512,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-06-28T00:00:00"
            },
            {
                "sd": 34085,
                "oj": "20-093-22-421-8",
                "odt": "2022-07-05T00:00:00",
                "opc": "Pc34085                                                                                                       ",
                "ofn": " ",
                "ocir": 601,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-03-17T00:00:00"
            },
            {
                "sd": 35054,
                "oj": "020-105-22-1668-07",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35054                                                                                                       ",
                "ofn": " ",
                "ocir": 600,
                "ofce": 1400,
                "ocy": 7,
                "ocs": "Cs2100",
                "oprty": 7,
                "ostl": 7,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35058,
                "oj": "20-045-22-1188-8",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35058                                                                                                       ",
                "ofn": " ",
                "ocir": 510,
                "ofce": 1270,
                "ocy": 1,
                "ocs": "Cs2",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-11T00:00:00"
            },
            {
                "sd": 35059,
                "oj": "020-054-22-955-08",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35059                                                                                                       ",
                "ofn": " ",
                "ocir": 540,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs27",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-05T00:00:00"
            },
            {
                "sd": 35061,
                "oj": "",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35061                                                                                                       ",
                "ofn": " ",
                "ocir": 620,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs6",
                "oprty": 8,
                "ostl": 0,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35062,
                "oj": "20-093-22-413-7",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35062                                                                                                       ",
                "ofn": " ",
                "ocir": 483.2,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 1,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35063,
                "oj": "020-093-22-1512-09",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35063                                                                                                       ",
                "ofn": " ",
                "ocir": 572,
                "ofce": 1300,
                "ocy": 1,
                "ocs": "Cs84",
                "oprty": 1,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35064,
                "oj": "20-073-22-1670-8",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35064                                                                                                       ",
                "ofn": " ",
                "ocir": 526,
                "ofce": 1100,
                "ocy": 8,
                "ocs": "Cs49",
                "oprty": 8,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35065,
                "oj": "020-084-19-11-08",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35065                                                                                                       ",
                "ofn": " ",
                "ocir": 480,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs70",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-03T00:00:00"
            },
            {
                "sd": 35070,
                "oj": "",
                "odt": "2022-10-12T00:00:00",
                "opc": "Pc35070                                                                                                       ",
                "ofn": " ",
                "ocir": 560,
                "ofce": 1300,
                "ocy": 5,
                "ocs": "Cs84",
                "oprty": 5,
                "ostl": 0,
                "orcy": 5,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35071,
                "oj": "020-075-22-786-03",
                "odt": "2022-10-13T00:00:00",
                "opc": "Pc35071                                                                                                       ",
                "ofn": " ",
                "ocir": 670,
                "ofce": 505,
                "ocy": 1,
                "ocs": "Cs2109",
                "oprty": 1,
                "ostl": 1,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35081,
                "oj": "20-073-22-1674-8",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35081                                                                                                       ",
                "ofn": " ",
                "ocir": 630,
                "ofce": 1100,
                "ocy": 8,
                "ocs": "Cs49",
                "oprty": 8,
                "ostl": 0,
                "orcy": 4,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35082,
                "oj": "020-084-22-1591-07",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35082                                                                                                       ",
                "ofn": " ",
                "ocir": 519,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs70",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-13T00:00:00"
            },
            {
                "sd": 35083,
                "oj": "020-073-22-1538-09",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35083                                                                                                       ",
                "ofn": " ",
                "ocir": 490,
                "ofce": 1320,
                "ocy": 1,
                "ocs": "Cs49",
                "oprty": 1,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35084,
                "oj": "020-084-22-1199-07",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35084                                                                                                       ",
                "ofn": " ",
                "ocir": 690,
                "ofce": 1400,
                "ocy": 2,
                "ocs": "Cs70",
                "oprty": 2,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35085,
                "oj": "020-002-21-2099-07",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35085                                                                                                       ",
                "ofn": " ",
                "ocir": 600,
                "ofce": 1500,
                "ocy": 4,
                "ocs": "Cs2106",
                "oprty": 4,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35086,
                "oj": "020-002-22-607-08",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35086                                                                                                       ",
                "ofn": " ",
                "ocir": 680,
                "ofce": 1500,
                "ocy": 3,
                "ocs": "Cs2106",
                "oprty": 3,
                "ostl": 0,
                "orcy": 2,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35087,
                "oj": "020-002-22-392-09",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35087                                                                                                       ",
                "ofn": " ",
                "ocir": 600,
                "ofce": 1500,
                "ocy": 1,
                "ocs": "Cs2106",
                "oprty": 1,
                "ostl": 0,
                "orcy": 0,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35088,
                "oj": "020-084-22-1577-09",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35088                                                                                                       ",
                "ofn": " ",
                "ocir": 510,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs70",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-13T00:00:00"
            },
            {
                "sd": 35089,
                "oj": "20-073-22-1490-6",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35089                                                                                                       ",
                "ofn": " ",
                "ocir": 620,
                "ofce": 1320,
                "ocy": 1,
                "ocs": "Cs49",
                "oprty": 0,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-13T00:00:00"
            },
            {
                "sd": 35090,
                "oj": "020-08422-1542-09",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35090                                                                                                       ",
                "ofn": " ",
                "ocir": 735,
                "ofce": 1400,
                "ocy": 3,
                "ocs": "Cs70",
                "oprty": 0,
                "ostl": 0,
                "orcy": 3,
                "ohg": 3,
                "oComDt": "2022-10-15T00:00:00"
            },
            {
                "sd": 35091,
                "oj": "020-084-22-1603-09",
                "odt": "2022-10-15T00:00:00",
                "opc": "Pc35091                                                                                                       ",
                "ofn": " ",
                "ocir": 570,
                "ofce": 1400,
                "ocy": 2,
                "ocs": "Cs70",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 1,
                "oComDt": "2022-10-15T00:00:00"
            },
            {
                "sd": 35092,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35092                                                                                                       ",
                "ofn": " ",
                "ocir": 566,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs49",
                "oprty": 8,
                "ostl": 8,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35093,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35093                                                                                                       ",
                "ofn": " ",
                "ocir": 566,
                "ofce": 1400,
                "ocy": 8,
                "ocs": "Cs49",
                "oprty": 8,
                "ostl": 8,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35094,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35094                                                                                                       ",
                "ofn": " ",
                "ocir": 490,
                "ofce": 1400,
                "ocy": 9,
                "ocs": "Cs49",
                "oprty": 9,
                "ostl": 9,
                "orcy": 9,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35095,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35095                                                                                                       ",
                "ofn": " ",
                "ocir": 490,
                "ofce": 1400,
                "ocy": 9,
                "ocs": "Cs49",
                "oprty": 9,
                "ostl": 9,
                "orcy": 9,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35096,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35096                                                                                                       ",
                "ofn": " ",
                "ocir": 730,
                "ofce": 1400,
                "ocy": 9,
                "ocs": "Cs70",
                "oprty": 9,
                "ostl": 0,
                "orcy": 9,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35097,
                "oj": "020-084-22-1676-05",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35097                                                                                                       ",
                "ofn": " ",
                "ocir": 780,
                "ofce": 1400,
                "ocy": 5,
                "ocs": "Cs70",
                "oprty": 5,
                "ostl": 5,
                "orcy": 5,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35098,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35098                                                                                                       ",
                "ofn": " ",
                "ocir": 564,
                "ofce": 1150,
                "ocy": 7,
                "ocs": "Cs50",
                "oprty": 7,
                "ostl": 0,
                "orcy": 7,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35099,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35099                                                                                                       ",
                "ofn": " ",
                "ocir": 471,
                "ofce": 1320,
                "ocy": 8,
                "ocs": "Cs81",
                "oprty": 8,
                "ostl": 8,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35100,
                "oj": "",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35100                                                                                                       ",
                "ofn": " ",
                "ocir": 540,
                "ofce": 1150,
                "ocy": 8,
                "ocs": "Cs50",
                "oprty": 8,
                "ostl": 0,
                "orcy": 8,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35102,
                "oj": "020-054-22-1249-06",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35102                                                                                                       ",
                "ofn": " ",
                "ocir": 558,
                "ofce": 1400,
                "ocy": 1,
                "ocs": "Cs27",
                "oprty": 1,
                "ostl": 0,
                "orcy": 1,
                "ohg": 0,
                "oComDt": "2022-10-16T00:00:00"
            },
            {
                "sd": 35103,
                "oj": "020-105-21-1708-07",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35103                                                                                                       ",
                "ofn": " ",
                "ocir": 640,
                "ofce": 1400,
                "ocy": 4,
                "ocs": "Cs2100",
                "oprty": 4,
                "ostl": 0,
                "orcy": 3,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35104,
                "oj": "020-073-21-254-07",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35104                                                                                                       ",
                "ofn": " ",
                "ocir": 480,
                "ofce": 1100,
                "ocy": 2,
                "ocs": "Cs49",
                "oprty": 2,
                "ostl": 0,
                "orcy": 2,
                "ohg": 0,
                "oComDt": null
            },
            {
                "sd": 35105,
                "oj": "020-073-19-49-07",
                "odt": "2022-10-16T00:00:00",
                "opc": "Pc35105                                                                                                       ",
                "ofn": " ",
                "ocir": 540,
                "ofce": 1100,
                "ocy": 3,
                "ocs": "Cs49",
                "oprty": 3,
                "ostl": 0,
                "orcy": 3,
                "ohg": 0,
                "oComDt": null
            }
        ]
    return (
        <div className='container table'>
            <Table className='table' striped bordered hover responsive>
                <thead className='text-center'>
                    <tr>
                        <th>index</th>
                        <th> test-1</th>
                        <th> test-2</th>
                        <th> test-3</th>
                        <th> test-4</th>
                        <th> test-5</th>
                        <th> test-6</th>
                        <th> test-7</th>
                        <th> test-8</th>
                        <th> test-9</th>
                        <th> test-10</th>
                        <th> test-11</th>
                        <th> test-12</th>
                         
                    </tr>
                </thead>
                <tbody>
                    
                        {dataTable.map((el, index) => (
                            <tr>
                                <td>{index}</td>
                                <td>{el.sd}</td>
                                <td>{el.oj}</td>
                                <td>{el.odt}</td>
                                <td>{el.ofn}</td>
                                <td>{el.ocir}</td>
                                <td>{el.ofce}</td>
                                <td>{el.ofce}</td>
                                <td>{el.ocy}</td>
                                <td>{el.oprty}</td>
                                <td>{el.ostl}</td>
                                <td>{el.ohg}</td>
                                <td>{el.oComDt}</td>

                            </tr>
                    ))}
                 
                </tbody>
            </Table>
        </div>
    )
}
